TCP_IP = '127.0.0.1'
TCP_PORT = 5005
BUFFER_SIZE = 1024

STANDARD_SIGNAL_VALUE = 1.0
CURRENT_STATE = 0
NEXT_STATE = 1
UPDATE = 2
LEFT_TRIM   = 50
RIGHT_TRIM  = 50
TIME_STEP = 1
STANDARD_THRESHOLD_VALUE = 50
BASAL_STATE = 0
MAX_INIT_STATE = 10
DELTA_POLARIZATION = 0.1


END_TASK_SIGNAL = "END_TASK"
NB_TRIALS_ULTRASOUND = 3
DELTA_TIME_ULTRASOUND = 0.2